SnackisUppgift/Pages/DmIndex.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SnackisUppgift.Areas.Identity.Data;
using SnackisUppgift.Data;
using SnackisUppgift.Models;

namespace SnackisUppgift.Pages
{
    public class DmIndexModel : PageModel
    {
        private readonly SnackisUppgiftContext _context;
        private readonly UserManager<SnackisUppgiftUser> _userManager;

        public DmIndexModel(SnackisUppgiftContext context, UserManager<SnackisUppgiftUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<DirectMessage> DirectMessages { get;set; }

        public async Task OnGetAsync()
        {
            var userId = _userManager.GetUserId(User);
            DirectMessages = await _context.DirectMessages
                .Where(dm => dm.ReceiverId == userId || dm.SenderId == userId)
                .Select(dm => new DirectMessage
                {
                    Id = dm.Id,
                    SenderId = dm.SenderId,
                    ReceiverId = dm.ReceiverId,
                    Sender = _context.Users.FirstOrDefault(u => u.Id == dm.SenderId),
                    Receiver = _context.Users.FirstOrDefault(u => u.Id == dm.ReceiverId),
                    Subject = dm.Subject,
                    Message = dm.Message,
                    SentAt = dm.SentAt
                })
                .OrderByDescending(dm => dm.SentAt) 
                .ToListAsync();
        }

        public async Task<IActionResult> OnPostSendDMAsync(string receiverEmail, string dmContent)
        {
            
            var receiver = await _userManager.FindByEmailAsync(receiverEmail);
            if (receiver == null)
            {
                ModelState.AddModelError("", "No user with that email found");
                return Page();
            }

           
            var senderId = _userManager.GetUserId(User);

            
            var dm = new DirectMessage
            {
                SenderId = senderId,
                ReceiverId = receiver.Id,
                Message = dmContent,
                SentAt = DateTime.UtcNow
            };

            _context.DirectMessages.Add(dm);
            await _context.SaveChangesAsync();

            

            return RedirectToPage();
        }
    }
}

SnackisUppgift/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SnackisUppgift.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

SnackisUppgift/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using SnackisUppgift.Areas.Identity.Data;
using SnackisUppgift.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SnackisUppgift.Pages
{
    public class IndexModel : PageModel
    {
        private readonly Data.SnackisUppgiftContext _context;
        private readonly UserManager<SnackisUppgiftUser> _userManager;

        public IndexModel(Data.SnackisUppgiftContext context, UserManager<SnackisUppgiftUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public ICollection<Comment> Comments { get; set; }
        public string ProfilePicture { get; set; }
        public List<Subject> Subjects { get; set; }
        public Models.Subject Subject { get; set; }
        public List<Models.Post> Posts { get; set; }
        [BindProperty]
        public Models.Post Post { get; set; }
        [BindProperty]
        public bool IsAnonymous { get; set; }
        public bool ShowForm { get; set; }
        public IFormFile UploadedImage { get; set; }
        public SnackisUppgiftUser MyUser { get; set; }

        public async Task<IActionResult> OnGetAsync(int subjectId = 0, int postId = 0, int deleteid = 0, bool showForm = false)
        {
            Comments = await _context.Comments
                .Include(c => c.User)
                .Include(c => c.ChildComments) 
                .Where(c => c.PostId == postId && c.ParentCommentId == null) 
                .ToListAsync();

            ShowForm = showForm;
            Subjects = await DAL.SubjectManagerAPI.GetAllSubjects();

            if (subjectId > 0) 
            {
                Subject = await DAL.SubjectManagerAPI.GetSubject(subjectId);
            }

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (!string.IsNullOrEmpty(userId))
            {
                MyUser = await _userManager.FindByIdAsync(userId);

                if (MyUser != null && MyUser.ProfilePicture != null) 
                {
                    if (Post == null)
                    {
                        Post = new Models.Post();
                    }
                    Post.ProfilePicture = MyUser.ProfilePicture;
                }
            }

            if (deleteid > 0) 
            {
                Models.Post blog = await _context.Post.FindAsync(deleteid);

                if (blog != null)
                {
                    var currentUser = await _userManager.GetUserAsync(User);

                    
                    if (User.IsInRole("Admin") || (currentUser != null && blog.UserName == currentUser.UserName) || User.IsInRole("Owner"))
                    {
                        if (System.IO.File.Exists("./wwwroot/img/" + blog.Image))
                        {
                            System.IO.File.Delete("./wwwroot/img/" + blog.Image);
                        }
                        _context.Post.Remove(blog);
                        await _context.SaveChangesAsync();
                        return RedirectToPage("./Index");
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "You are not authorized to delete this post.";
                        return RedirectToPage("./Index");
                    }
                }
            }

            
            if (subjectId > 0) 
            {
                Posts = await _context.Post
                    .Where(p => p.SubjectId == subjectId)
                    .OrderByDescending(p => p.Date)
                    .ToListAsync();
            }
            else
            {
                Posts = await _context.Post
                    .OrderByDescending(p => p.Date)
                    .ToListAsync();
            }

            
            foreach (var post in Posts)
            {
                post.Comments = await _context.Comments
                    .Include(c => c.User)
                    .Include(c => c.ChildComments) 
                    .Where(c => c.PostId == post.Id && c.ParentCommentId == null) 
                    .ToListAsync();
            }

            return Page();
        }


        [HttpPost]
		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				
				Subjects = await DAL.SubjectManagerAPI.GetAllSubjects();
				return Page();
			}

			string filename = string.Empty;
			if (UploadedImage != null)
			{
				Random rnd = new();
				filename = rnd.Next(0, 100000).ToString() + UploadedImage.FileName;
				var file = "./wwwroot/img/" + filename;
				using (var filestream = new FileStream(file, FileMode.Create))
				{
					await UploadedImage.CopyToAsync(filestream);
				}
			}
			var user = await _userManager.FindByIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));

			Post.Date = DateTime.Now;
			Post.Image = filename;

			if (IsAnonymous == true)
			{
				Post.UserName = null;
			}
			else
			{
				Post.UserName = user.UserName;
				if (user.ProfilePicture != null)
				{
					Post.ProfilePicture = user.ProfilePicture;
				}
			}

			_context.Add(Post);
			await _context.SaveChangesAsync();

			return RedirectToPage("./Index");
		}

		public async Task<IActionResult> OnPostDeleteAsync(int deleteId)
		{
			var post = await _context.Post.FindAsync(deleteId);
			if (post == null)
			{
				return NotFound();
			}

			
			var comments = _context.Comments.Where(c => c.PostId == deleteId).ToList();
			_context.Comments.RemoveRange(comments);

			_context.Post.Remove(post);
			await _context.SaveChangesAsync();

			return RedirectToPage("./Index");
		}



		public async Task<IActionResult> OnPostPostCommentAsync(int postId, string text)
        {
            var user = await _userManager.GetUserAsync(User);
            var post = await _context.Post.FindAsync(postId);

            if (user == null || post == null)
            {
                return BadRequest();
            }

            var comment = new Comment
            {
                Text = text,
                DatePosted = DateTime.Now,
                UserId = user.Id,
                PostId = postId,
                ProfilePicture = user.ProfilePicture
            };

            _context.Comments.Add(comment);
            await _context.SaveChangesAsync();

            return RedirectToPage();
        }

		public async Task<IActionResult> OnPostDeleteCommentAsync(int commentId)
		{
			var comment = await _context.Comments.FindAsync(commentId);

			if (comment != null)
			{
				var currentUser = await _userManager.GetUserAsync(User);

				
				if (currentUser != null && (comment.UserId == currentUser.Id || User.IsInRole("Admin") || User.IsInRole("Owner")))
				{
					_context.Comments.Remove(comment);
					await _context.SaveChangesAsync();
				}
			}

			return RedirectToPage();
		}
		public async Task<IActionResult> OnPostReportPostAsync(int postId, string category, string reason)
		{
			var post = await _context.Post.FindAsync(postId);

			if (post == null)
			{
				return NotFound();
			}

			
			post.Reports++;

			var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

			var postReport = new PostReport
			{
				PostId = postId,
				Category = category,
				Reason = reason,
				UserId = userId,
				CreatedDate = DateTime.Now
			};

			_context.PostReport.Add(postReport);
			await _context.SaveChangesAsync();

			return RedirectToPage();
		}





		public async Task<IActionResult> OnPostToggleLikeAsync(int postId)

		{
			var userId = _userManager.GetUserId(User);

			var existingLike = await _context.PostLike
				.FirstOrDefaultAsync(pl => pl.PostId == postId && pl.UserId == userId);

			var post = await _context.Post.FindAsync(postId);
			if (post == null)
			{
				return NotFound();
			}

			if (existingLike == null)
			{
				post.Likes++;
				var newLike = new PostLike { PostId = postId, UserId = userId };
				_context.PostLike.Add(newLike);
			}
			else
			{
				post.Likes--;
				_context.PostLike.Remove(existingLike);
			}

			await _context.SaveChangesAsync();

			return RedirectToPage();
		}




	}
}

SnackisUppgift/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SnackisUppgift.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

SnackisUppgift/Pages/Reply.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SnackisUppgift.Areas.Identity.Data;
using SnackisUppgift.Data;
using SnackisUppgift.Models;

namespace SnackisUppgift.Pages
{
	public class ReplyModel : PageModel
	{
		private readonly SnackisUppgiftContext _context;
		private readonly UserManager<SnackisUppgiftUser> _userManager;

		public ReplyModel(SnackisUppgiftContext context, UserManager<SnackisUppgiftUser> userManager)
		{
			_context = context;
			_userManager = userManager;
		}

		public DirectMessage OriginalMessage { get; set; }

        public async Task OnGetAsync(int id)
        {
            OriginalMessage = await _context.DirectMessages.FindAsync(id);

            if (OriginalMessage == null)
            {
                NotFound();
            }
        }

        public async Task<IActionResult> OnPostAsync(int id, string replyContent)
        {
            
            var originalMessage = await _context.DirectMessages.FindAsync(id);
            if (originalMessage == null)
            {
                return NotFound();
            }

          
            var reply = new DirectMessage
            {
                SenderId = _userManager.GetUserId(User),
                ReceiverId = originalMessage.SenderId,
                Subject = "RE: " + originalMessage.Subject,
                Message = replyContent,
                SentAt = DateTime.UtcNow
            };

            _context.DirectMessages.Add(reply);
            await _context.SaveChangesAsync();

            return RedirectToPage("DmIndex");
        }
    }
}

SnackisUppgift/Pages/DmIndex.cshtml
@page
@model SnackisUppgift.Pages.DmIndexModel
<style>
    body {
        background-image: url('/Backgroundimages/Chattbild.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        color:aqua
    }

    .blurry-background::before {
        content: "";
        display: block;
        position: fixed;
        z-index: -1;
        width: 100%;
        height: 100%;
        background: inherit;
        filter: blur(5px);
        transform: scale(1.1);
    }
</style>
<body class="blurry-background">
<div class="container">
    <h1 class="mt-5 mb-4">Report someones bad behavior</h1>

    @foreach (var dm in Model.DirectMessages)
    {
        <div class="card mb-3">
            <div class="card-header">
                From: @dm.Sender.UserName 
                To: @dm.Receiver.UserName 
            </div>
            <div class="card-body">
                <h5 class="card-title">@dm.Subject</h5>
                <p class="card-text">@dm.Message</p>
                <p class="card-text"><small class="text-muted">Sent: @dm.SentAt</small></p>
                <a asp-page="./Reply" asp-route-id="@dm.Id" class="btn btn-primary">Reply</a>
            </div>
        </div>
    }
</div>

<div class="container mt-5">
    <div class="accordion" id="sendDmAccordion">
        <div class="card">
            <div class="card-header" id="sendDmHeading">
                <button class="btn btn-link" type="button" data-bs-toggle="collapse" data-bs-target="#sendDmCollapse" aria-expanded="true" aria-controls="sendDmCollapse">
                    Send report
                </button>
            </div>
            <div id="sendDmCollapse" class="collapse" aria-labelledby="sendDmHeading" data-bs-parent="#sendDmAccordion">
                <div class="card-body">
                    <form method="post" asp-page-handler="SendDM">
                        <div class="form-group">
                            <label for="receiverEmail">email of the person you want to Report</label>
                            <input type="email" id="receiverEmail" name="receiverEmail" class="form-control">
                        </div>
                        <div class="form-group">
                                <label for="dmContent">Describe what the person has done</label>
                            <textarea id="dmContent" name="dmContent" class="form-control"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Send Report</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

SnackisUppgift/Pages/Reply.cshtml
@page
@model SnackisUppgift.Pages.ReplyModel
<head>
    <style>
        body {
            background-image: url('/Backgroundimages/Chattbild.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

        .blurry-background::before {
            content: "";
            display: block;
            position: fixed;
            z-index: -1;
            width: 100%;
            height: 100%;
            background: inherit;
            filter: blur(5px);
            transform: scale(1.1);
        }
        body {
            font-family: 'Arial', sans-serif;
            background-color: #F0F0F0;
            padding: 20px;
        }

        .container {
            max-width: 800px;
            margin: auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px #888;
        }

        .form-group {
            margin-bottom: 1rem;
        }

        h1 {
            color: #007bff;
            font-weight: bold;
            margin-bottom: 1rem;
            text-align: center;
        }

        p {
            margin-bottom: 1rem;
            line-height: 1.6;
            color: #333;
        }

        #replyContent {
            height: 150px;
            resize: vertical;
        }

        .btn-primary {
            color: #fff;
            background-color: #007bff;
            border-color: #007bff;
            width: 100%;
            padding: 10px;
            font-size: 18px;
            border-radius: 5px;
        }

        label {
            font-weight: bold;
            color: #666;
            display: block;
            margin-bottom: 5px;
        }

        input, textarea {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            width: 100%;
            box-sizing: border-box;
        }

        #email {
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Reply to Message</h1>

        <form method="post">
            <input type="hidden" asp-for="OriginalMessage.Id" />
            <input type="hidden" id="email" name="email" class="form-control" asp-for="OriginalMessage.Sender.Email">
            <div class="form-group">
                <label for="replyContent">Your Reply</label>
                <textarea id="replyContent" name="replyContent" class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Send Reply</button>
        </form>

        <p>@Model.OriginalMessage.Message</p>
    </div>
</body>